invirtVersion = 5.5.1

awaitilityVersion = 4.3.0
http4kVersion = 6.60.0.0
jacksonVersion = 2.22.2
kafkaVersion = 4.3.1
kotestVersion = 6.2.5
kotlinLoggingVersion = 8.0.03
kotlinVersion = 2.4.20
mockkVersion = 1.14.9
mongoDriverVersion = 5.7.0
testContainersVersion = 2.0.5
validkVersion = 3.2.0

org.gradle.parallel = true
org.gradle.workers.max = 2
